[template]
prefix = "/network_metadata"
src = "exabgp.tmpl"
dest = "/etc/exabgp/exabgp.conf"
owner = "root"
mode = "0644"
keys = [
  "nodes",
  "racks",
]
#check_cmd = "true" #"birdc -s /run/bird/bird_tor{{"%02d"|format(rack_number)}}.ctl sh proto"
#reload_cmd = "birdc -s /run/bird/bird_tor{{"%02d"|format(rack_number)}}.ctl configure"