---
- name: Install Docker-related packages
  block:
  - package:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
        - docker.io
        - python3-docker

- name: Install and run ETCD
  block:
  - copy: src=etcd.sh dest=/usr/local/bin/ owner=root mode=755
  - docker_image: name=quay.io/coreos/etcd:latest
  - template: src="etcd_systemd_unit.j2" dest="/etc/systemd/system/etcd.service"
    register: etcd_unit_installed
  - command: systemctl daemon-reload
    when: etcd_unit_installed.changed
  - service: name=etcd enabled=yes state=started

- name: Install ETCDCTL
  block:
  - command: test -x /usr/local/bin/etcdctl
    register: etcdctl_installed
    ignore_errors: True
  - command: docker cp etcd.service:/usr/local/bin/etcdctl /usr/local/bin/etcdctl
    when: etcdctl_installed is failed
  - file: path=/usr/local/bin/etcdctl mode=755
    when: etcdctl_installed is failed

- name: Upload network_metadata to ETCD
  block:
  - copy: src=../../../../tmp/network_metadata.yaml dest=/etc/
  - command: etcdctl ls /network_metadata
    register: network_metadata_uploaded
    ignore_errors: True
  - command: etcdtool import -y -f yaml /network_metadata /etc/network_metadata.yaml
    when: network_metadata_uploaded is failed
    register: network_metadata_loaded_to_etcd
  - command: /usr/local/bin/etcd.sh backup
    environment:
      ETCD_IPV4: "{{ master_node_ipaddr }}"
    when: network_metadata_loaded_to_etcd.changed

- name: Install and start BIRD bgpd
  block:
  - apt_repository: repo='ppa:cz.nic-labs/bird'
  - package: name=bird state=latest update_cache=yes
  - file: path=/etc/init/bird.override state=absent
  - copy: src=bird_master.toml dest=/etc/confd/conf.d/bird.toml
  - copy: src=bird_master.tmpl dest=/etc/confd/templates/bird.tmpl
  - name: Generate main BIRD config by confd
    command: confd -onetime
    environment:
      HOSTNAME: "{{ node_name }}"
    ignore_errors: True
  - file: path=/var/log/bird state=directory owner=bird group=bird mode=755
  - copy: dest=/var/log/bird/master.log content="Use 'journalctl -u bird' for looking log."
  - name: disable start of bird6 service
    file: path=/etc/bird/bird6.conf state=absent
  - service: name=bird6 enabled=no state=stopped
  - service: name=bird enabled=yes state=reloaded

- name: Virtual router main script
  block:
  - copy: src=virt-router.sh dest=/usr/local/bin/virt-router.sh
    register: virt_router_installed
  - file: path=/usr/local/bin/virt-router.sh mode=755
    when: virt_router_installed.changed
  - name: Virtual router unit
    copy: src=tor_unit.service dest=/etc/systemd/system/tor@.service
    register: virt_router_unit_installed
  - command: systemctl daemon-reload
    when: virt_router_unit_installed.changed

- name: Vartual racks
  debug:
    msg: "{{virt_racks}}"

- name: Configure virtual TOR
  include_tasks: rack.yaml
  loop: "{{virt_racks|unique}}"
  loop_control:
    loop_var: rack_number